### PR TITLE
Add QLik API Integration

### LINKED ISSUE #1: QLik API Integration
It turns out that that the QLik Sense (the product which powers the graphs on the page) [has a remarkably well-documented API](https://help.qlik.com/en-US/sense-developer/May2021/Subsystems/EngineAPI/Content/Sense_EngineAPI/introducing-engine-API.htm) which provides data a lot more accurately than the current scraping process using Puppeteer.

### Advantages of this approach
- Decimals will no longer be rounded. For example, the positive test percentage for Australia yesterday was `0.0014373561076329474`, but the scraped data is rounded to `0.1`
- Scraping is much faster now - [my implementation takes ~12 seconds](https://github.com/llui85/covid19stats-govau/runs/3005226945?check_suite_focus=true) compared to the current ~1 minute.
- The API provides a modification datetime as ISO8601, so the regex that looks for a date in the footnote can be now avoided:

https://github.com/jxeeno/aust-govt-covid19-stats/blob/26790ca22d8cc206dfd73622bd745bc5b235f6bf/scrape.js#L14-L25

Unfortunately we still need to hardcode the ID of each graph as graph titles aren't included for some reason, but these don't change often, and will still be stored in the raw data.

I'm happy to open a PR for this sometime in the next week if you'd like me to. You can see my [basic implementation here](https://github.com/llui85/covid19stats-govau/blob/master/index.js).

### PR DESCRIPTION
**Pull request by llui85**
Closes #1

Here's my (hopefully) complete implementation of the QLik API for this project. In some ways this is similar to my previous example implementation, however I have greatly improved the code quality, added comments where necessary and made these changes backwards-compatible with previous data.

## Summary of changes
- `puppeteer` and `cheerio` have been removed from the project dependencies as they are no longer needed.
- `node-fetch` and `ws` have been added to the project dependencies.
- Two configuration options have been added to `scrape.js` - `PAGE_URI` for the page url which contains the graphs, and `QLIK_WS_PREFIX` which is the prefix for the QLik Sense server.
- Two new folders have been created in `data/docs` to store the new raw data in - `raw-new` and `rawhtml-new`.
- A new script `create-legacy-data.js` has been added, which turns the new raw files into old files. As a result of this, this change data source should be fully backwards compatible for any consumers. This script should be run before generating the CSV data.
- The GitHub action has been modified to run `create-legacy-data.js` before `generate-csv.js`. I have also separated the `yarn install` command into a separate step, removed the puppeteer image (which should vastly increase the action speeds) and removed the step which installs git (as it is already installed).
- The README has been updated with the new script in the "To run yourself" section
- **`generate-csv.js` has not been updated as no changes are necessary**

## Possibly breaking changes
The files in the `docs/data/raw` directory, `all.csv`, `all.json` have the following changes which may impact data consumers:
- Numbers are no longer comma-separated or truncated.
- Percentages are no longer prefixed with a percentage symbol.

This can be seen in the below images. **The new files are shown on the left.**
tests-comparison
source-comparison

Best wishes,
**llui85**

### CODE REVIEW

**Comment by llui85** [comment]
Also, @jxeeno would you mind licensing this repository under an open source license?

**Comment by jxeeno** [comment]
Thank you so much @llui85.  I'll review tonight and notify some of the downstream users that I know of to make sure they're aware of the potentially breaking changes.

And thanks for the reminder re license -- we're now using CC0.

**Comment by jxeeno** [comment]
LGTM! Thanks for putting this together, @llui85. Much appreciated 🙏

**Comment by jxeeno** [comment]
Heads up @llui85 , it turns out `modifiedDate` can change without the data changing!  We may have to go back to the regex 🙃

**Comment by llui85** [comment]
@jxeeno Do you think it would be enough to remove the check that the raw data still exists when writing the file? I think it would work, as the data will update later, but could mean inaccurate data for the current day, which isn't ideal.
https://github.com/jxeeno/aust-govt-covid19-stats/blob/92f25518702c46a83341ec29f3bf30f73e69e494/scrape.js#L202-L209

**Comment by llui85** [comment]
Also, there are a few other date properties which might be what we want. Does `qLastReloadTime` or `qMeta.createdDate` have the correct value?
```
{
	"0": {
		"qDocName": "COVID-19 - NIR External Report",
		"qConnectedUsers": 0,
		"qFileTime": 0,
		"qFileSize": 556269,
		"qDocId": "e8635e3f-b339-4ab3-a9de-b4e3b15c6bbc",
		"qMeta": {
			"createdDate": "2021-07-08T05:11:22.498Z",
			"modifiedDate": "2021-07-08T10:00:05.986Z",
			"published": true,
			"publishTime": "2021-07-08T10:00:04.556Z",
			"privileges": [
				"read"
			],
			"description": "r6.4 Release",
			"dynamicColor": "hsla(187,18%,43%,1)",
			"create": null,
			"stream": {
				"id": "aaec8d41-5201-43ab-809f-3063750dfafd",
				"name": "Everyone"
			},
			"canCreateDataConnections": false
		},
		"qLastReloadTime": "2021-07-08T04:32:59.426Z",
		"qTitle": "COVID-19 - NIR External Report",
		"qThumbnail": {
			"qUrl": "/appcontent/e8635e3f-b339-4ab3-a9de-b4e3b15c6bbc/30layer.PNG"
		}
	}
}
```

**Pull request merged**
